"""user table created

Revision ID: 54f7f1f62c4b
Revises: 20b9a0dbac1a
Create Date: 2025-02-11 01:54:11.177248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f7f1f62c4b'
down_revision = '20b9a0dbac1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
