version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: blog_db
    environment:
      - POSTGRES_USER=dummy
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blogdb
    ports:
      - "5460:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blog-network

volumes:
  postgres-data:

networks:
  blog-network:
    driver: bridge
