# Generated by Django 5.1.5 on 2025-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=11)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
    ]
