version: '3.8'

services: 
  db:
    image: postgres:latest
    container_name: Practice_Blog_DB
    environment:
      - POSTGRES_USER=dummy
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5469:5432" 
    # Expose PostgreSQL on port 5455 of the host
    networks:
      - blog-network
 
volumes:
  postgres_data:
  
networks:
  blog-network:
    driver: bridge